### ISSUE TITLE
Add  nav bar in all 3 event pages

### ISSUE THREAD

**Issue by AshishkrGoyal** [opensrc-org/opensrc-org.github.io#11]

**Comment by AshishkrGoyal** [comment]
@hit-11 you want to work on it or not ??
updates ASAP!!

Thanks 👍

**Comment by hit-11** [comment]
@AshishkrGoyal Sorry I got busy somewhere else so couldn't fix it. But now I'm on it . will update u soon . :+1:

**Comment by hit-11** [comment]
@AshishkrGoyal done boss :smile: fix#11
