### ISSUE TITLE
about us is merging into leaders section

### ISSUE THREAD

**Issue by AshishkrGoyal** [opensrc-org/opensrc-org.github.io#19]
@hit-11 
give a view to website and after keen observation you will find that about us section is merging into our leaders section, you can find this by observing background color.

try to fix it ASAP!!

Thanks 👍

**Comment by AshishkrGoyal** [comment]
@hit-11 it is your fault when u add navigation bar to event page, by the mistake CSS had been changed and due to this About Us background change.
At my local everything is working file.
so please first submit a PR, then after review i will merge it 

Thanks for ur contribution 👍

**Comment by hit-11** [comment]
Sorry for the error ! I'll be careful next time.
