### ISSUE TITLE
change the styling of navigation bar(team sec) to default 

### ISSUE THREAD

**Issue by AshishkrGoyal** [opensrc-org/opensrc-org.github.io#24]
@hit-11 
![image](https://user-images.githubusercontent.com/25322851/32235646-0dfca13a-be86-11e7-9442-a7eee215895a.png)
change the styling of nav bar like home page navigation bar..
Thanks 👍

**Comment by hit-11** [comment]
@AshishkrGoyal 
[https://screenshots.firefox.com/F3HFrKrFx2J3Skk3/null](url)
The entire styling of the navbar has been done like the home page. But there is a white space occuring above the navbar. Pls look into the matter.(screenshot attached)

**Comment by AshishkrGoyal** [comment]
@hit-11 url is not working

**Comment by AshishkrGoyal** [comment]
![image](https://user-images.githubusercontent.com/25322851/32278721-938a651a-bf3c-11e7-9b8d-13d469d48ec9.png)
same as earlier no changes occured

**Comment by hit-11** [comment]
@AshishkrGoyal [https://drive.google.com/open?id=0B8L1JqndMZFCVFpMUkZTcG5WTlk](url)
No changes have occured because  i have not commited those changes yet.

**Comment by AshishkrGoyal** [comment]
@hit-11 send pr then i will tell you one thing which should be modified
